### ISSUE TITLE
Better release experience with Songmu/tagpr

### ISSUE THREAD

**Issue by 5ouma** [5ouma/mli#38]
### ✏️ Describe the feature

[Songmu/tagpr](https://github.com/Songmu/tagpr) automatically creates a PR to track unreleased changes.
The maintainer only needs to merge that PR to release a new version.

### ✔︎ Confirm these checks

- [X] I searched the GitHub [Issues](https://github.com/5ouma/mli/issues) or [Discussions](https://github.com/5ouma/mli/discussions).
- [X] I tried with the latest version.
- [X] I agree to follow the [Code of Conduct](https://github.com/5ouma/mli/blob/main/.github/CODE_OF_CONDUCT.md).
