### ISSUE TITLE
Update the Go version itself

### ISSUE THREAD

**Issue by 5ouma** [5ouma/mli#45]
### ✏️ Describe the feature

The Go version in `go.mod` is not updated automatically, so GitHub Actions should update it.

### ✔︎ Confirm these checks

- [X] I searched the GitHub [Issues](https://github.com/5ouma/mli/issues) or [Discussions](https://github.com/5ouma/mli/discussions).
- [X] I tried with the latest version.
- [X] I agree to follow the [Code of Conduct](https://github.com/5ouma/mli/blob/main/.github/CODE_OF_CONDUCT.md).

### 🗒️ Additional Information

You can get the latest Go version from `https://go.dev/VERSION?m=text`.
